# Generated by Django 4.0.2 on 2022-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCaption', models.TextField(max_length=50)),
                ('imageGallery', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
