# Generated by Django 4.0.2 on 2022-05-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='add_gallery',
        ),
    ]
